### PR TITLE
[CI] Add test framework (using pytest)

### PR DESCRIPTION
**Pull request by vivekkrish**
Hey @tanghaibao,

I've created a new branch which adds a testing framework to the `jcvi` repo. This can be considered to be a form of functional testing, as it validates the functionality of an ACTION (`jcvi.formats.gff format`) within a particular SCRIPT (`jcvi.formats.gff`).

This testing functionality was adapted from the implementation developed by https://github.com/CGATOxford/cgat.

Here is an outline of the testing framework:
1. The `tests/` directory contains within it, the same folder structure as the top-level of the `jcvi` repo. For example, tests for `gff.py` will be stored in `tests/formats/gff.py/*`.
2. Tests are configured via a `yml` format file, which defines the **test name**, **action**, **args**, **inputs**, **outputs**, and **references**. For example, see [`tests/formats/gff.py/tests.yml`](https://github.com/tanghaibao/jcvi/blob/master-add-tests/tests/formats/gff.py/tests.yml) in this branch.
3. The config information is used to build a series of parametrized tests and execute them in order.
3. Upon execution of a tests, its **outputs** (stored in temporary files) are compared against **reference** files to confirm whether the test passed or failed.

This PR sets up the framework and adds sample tests for ACTIONS within `jcvi.formats.gff()`.

Could you please take a look and let me know what you think?

Thank you!

### CODE REVIEW

**Comment by vivekkrish** [comment]
I'm currently in the process of checking to see why these sample tests are failing when executed by travis, but passing successfully on my filesystem:
```
$ py.test --tb=short tests/
============================================================================================================ test session starts =============================================================================================================
platform linux2 -- Python 2.7.3, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/vkrishna/git/tanghaibao/jcvi, inifile:
collected 26 items

tests/test_scripts.py ..........................                                                                                                                                                                                       [100%]

========================================================================================================= 26 passed in 19.78 seconds =========================================================================================================
```

**Comment by tanghaibao** [comment]
@vivekkrish 
This looks fantastic - is it possible to get rid of the error messages for the tests?
Currently there are a couple failing. Fixing or disabling the tests would be ideal.

Haibao

**Comment by tanghaibao** [comment]
@vivekkrish 
Another comment, perhaps a minor one, is to move all the sample datasets to a common folder, for example `tests`, instead of placing along side the code.

Haibao

**Comment by vivekkrish** [comment]
@tanghaibao, thanks for your comments! I am trying to fix the tests since there seems to be something different in the environment used by travis vs my machine, which seems to be causing a discrepancy in the outcome of the tests.

Regarding your other comment about the sample datasets, they are already within a sub-folder called [`tests/`](https://github.com/tanghaibao/jcvi/tree/master-add-tests/tests), please take a look. Thank you!

**Comment by zhiquanyang** [comment]
Dear Tang,
      Could you offer a pipline how to use jcvi to get the LF,MF1,MF2 regions from Brassica rapa genome?
Zhiquan

**Comment by tanghaibao** [comment]
@zhiquanyang 

Unfortunately no. The work of LF, MF1 and MF2 assignments in *Brassica rapa* required some non-trivial steps that this repo does not yet have the code for.

Haibao

**Comment by zhiquanyang** [comment]
> @zhiquanyang
> 
> Unfortunately no. The work of LF, MF1 and MF2 assignments in _Brassica rapa_ required some non-trivial steps that this repo does not yet have the code for.
> 
> Haibao

**Comment by zhiquanyang** [comment]
Dear Tang,
I see. Thanks for your answer. I want to use Mcscan to get three alignment regions corresponding to the same region in Arabidopsis genome, like this,
 `python -m jcvi.compara.synteny mcscan TAIR.bed TAIR.Bra.lifted.anchors --iter=1 -o TAIR.Bra.i1.blocks`
And then use manual to filter these region. Do you think it is feasible ?
Zhiquan

**Comment by vivekkrish** [comment]
Hey Haibao, thanks for resolving the issue and merging the PR! Just realizing that due to how this testing framework is set up (to execute the python scripts instead of importing them), it doesn't play well with code coverage tracking.

If you see this message in the log, https://travis-ci.org/tanghaibao/jcvi/builds/491332657#L1607, it says module jcvi was never imported.

This is because the tester explicitly executes a particular script like so:
https://github.com/tanghaibao/jcvi/blob/6a905d429c9d477238013669e95a98e23403cc5c/tests/test_scripts.py#L103-L105

Any thoughts on how to get around this?

**Comment by tanghaibao** [comment]
@vivekkrish 

Great suggestions. In commit d7c6aeb, I changed it so that it dynamically imports a module and the function (based on the YAML file) and call it within Python. I just needed to find out a way to re-route `sys.stdout` to a file handle so I googled it.

I also had to change a test case within the YAML file (`gff.merge`) since I don't know an easy way to allow wild cards (e.g. `*.gff`) and pass it to Python.

Fantastic test framework. Sorry it took so long for me to get this in.

Haibao

**Comment by vivekkrish** [comment]
Thanks @tanghaibao! Seems like a straightforward fix. Looks great now!

For args with wildcards, could you do a `glob` expansion before calling the import function? 

This framework drew a lot of inspiration from the work done by CGAT. Glad that it is integrated! I'm hoping that I can spend some time in the near future to add documentation and more functional tests to cover the different modules.

**Pull request merged**
